                                                                                                                                                                                                                                                                  const hasChanged = JSON.stringify(nextBoard) !== JSON.stringify(prevBoard);
                                                                                                                                                                                                                                                                            return hasChanged ? addRandomTile(nextBoard) : prevBoard;
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                  window.addEventListener('keydown', handleKeyDown);
                                                                                                                                                                                                                                                                                                      return () => {
                                                                                                                                                                                                                                                                                                            window.removeEventListener('keydown', handleKeyDown);
                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                  }, [board]);

                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                        <div className="container">
                                                                                                                                                                                                                                                                                                                              <div className="board">
                                                                                                                                                                                                                                                                                                                                      {board.map((row, rowIndex) => (
                                                                                                                                                                                                                                                                                                                                                <div className="row" key={rowIndex}>
                                                                                                                                                                                                                                                                                                                                                            {row.map((cell, cellIndex) => (
                                                                                                                                                                                                                                                                                                                                                                          <div 
                                                                                                                                                                                                                                                                                                                                                                                          key={cellIndex} 
                                                                                                                                                                                                                                                                                                                                                                                                          className={`cell ${cell === 0 ? 'cell-0' : 'cell-1'}`}
                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                        {cell !== 0 ? cell : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default App;