                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                          <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                    <div className="form-group">
                                                                                                                                                                                                                                                                <label htmlFor="name">Name:</label>
                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                                                                        id="name"
                                                                                                                                                                                                                                                                                                                      value={name}
                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                  <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                              <label htmlFor="email">Email:</label>
                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                        type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                      id="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" disabled={status === 'loading'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {status === 'loading' ? 'Submitting...' : 'Subscribe'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {status === 'error' && <p className="error-message">{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default NewsletterForm;
       