                                                                                                                                                        value={newTodo}
                                                                                                                                                                  onChange={(e) => setNewTodo(e.target.value)}
                                                                                                                                                                            placeholder="Add a new todo"
                                                                                                                                                                                    />
                                                                                                                                                                                            <button type="submit">Add Todo</button>
                                                                                                                                                                                                  </form>

                                                                                                                                                                                                        {todos.length === 0 ? (
                                                                                                                                                                                                                <p className="empty-message">No todos</p>
                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                              <ul>
                                                                                                                                                                                                                                        {todos.map((todo) => (
                                                                                                                                                                                                                                                    <li
                                                                                                                                                                                                                                                                  key={todo.id}
                                                                                                                                                                                                                                                                                className={`todo-item ${todo.completed ? 'completed' : ''}`}
                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                          <label>
                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                            type="checkbox"
                                                                                                                                                                                                                                                                                                                                                              checked={todo.completed}
                                                                                                                                                                                                                                                                                                                                                                                onChange={() => toggleComplete(todo.id)}
                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                {todo.text}
                                                                                                                                                                                                                                                                                                                                                                                                                              </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default App;