                                                                                                                                                                                                                                                                                                                                                                                      return () => {
                                                                                                                                                                                                                                                                                                                                                                                            window.removeEventListener('keydown', handleKeyDown);
                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                  }, [board]);

                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="container">
                                                                                                                                                                                                                                                                                                                                                                                                              {/* Restart Button with the required class name */}
                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="restart" onClick={restartGame}>
                                                                                                                                                                                                                                                                                                                                                                                                                            Restart
                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="board">
                                                                                                                                                                                                                                                                                                                                                                                                                                                {board.map((row, rowIndex) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="row" key={rowIndex}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {row.map((cell, cellIndex) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={cellIndex} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`cell ${cell === 0 ? 'cell-0' : 'cell-1'}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {cell !== 0 ? cell : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {gameOver && <div className="game-over">Game Over</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default App;